[package]
name = "tracing-stackdriver"
version = "0.1.0"
authors = ["Alex Pearson <alex@alexpear.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/NAlexPear/tracing-stackdriver"
description = "Stackdriver-compatible tracing Subscriber"
keywords = ["tracing", "stackdriver", "logging"]

[badges]
github = { repository = "NAlexPear/tracing-stackdriver" } 
maintenance = { status = "actively-developed" }

[dependencies]
futures = "0.3.4"
Inflector = "0.11.4"
serde_json = "1"
tracing-core = "0.1.10"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-serde = "0.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dev-dependencies]
lazy_static = "1.4"
tracing = "0.1"
